# =========================
# Unified schema for ALL tools
# item = {
#   "id": str,
#   "domain": "ms_settings" | "control_panel" | "system_tool",
#   "title": str,
#   "description": str,   # retrieval-friendly: includes common user phrases / synonyms
#   "launch": {
#       "kind": "uri" | "control_name" | "cpl" | "control_home" | "exe" | "msc",
#       "value": str,
#       "args": list[str]   # optional; present when needed
#   }
# }
# =========================


MS_SETTINGS_ITEMS = {
    # —— Accounts / User Accounts ——
    "ms-settings:workplace": {
        "id": "ms-settings:workplace",
        "domain": "ms_settings",
        "title": "Workplace / Access work or school",
        "description": "Windows Settings → Accounts. Connect or disconnect a work/school account, manage workplace access, device management enrollment, MDM, and organizational sign-in.",
        "launch": {"kind": "uri", "value": "ms-settings:workplace", "args": []},
    },
    "ms-settings:emailandaccounts": {
        "id": "ms-settings:emailandaccounts",
        "domain": "ms_settings",
        "title": "Email & accounts",
        "description": "Windows Settings → Accounts → Email & accounts. Add/remove email accounts, Microsoft accounts, and app accounts used by Mail, Calendar, and other apps.",
        "launch": {"kind": "uri", "value": "ms-settings:emailandaccounts", "args": []},
    },
    "ms-settings:otherusers": {
        "id": "ms-settings:otherusers",
        "domain": "ms_settings",
        "title": "Other users / Family & other users",
        "description": "Windows Settings → Accounts → Other users. Add local users, add family members, set up kiosk/assigned access, manage user accounts on this PC.",
        "launch": {"kind": "uri", "value": "ms-settings:otherusers", "args": []},
    },
    "ms-settings:assignedaccess": {
        "id": "ms-settings:assignedaccess",
        "domain": "ms_settings",
        "title": "Assigned access / Kiosk",
        "description": "Windows Settings → Accounts → Assigned access. Configure kiosk mode, single-app/limited user experience, lock down a device for public use.",
        "launch": {"kind": "uri", "value": "ms-settings:assignedaccess", "args": []},
    },
    "ms-settings:signinoptions": {
        "id": "ms-settings:signinoptions",
        "domain": "ms_settings",
        "title": "Sign-in options",
        "description": "Windows Settings → Accounts → Sign-in options. Configure PIN, password, Windows Hello face/fingerprint, security key, lock screen sign-in, and sign-in requirements.",
        "launch": {"kind": "uri", "value": "ms-settings:signinoptions", "args": []},
    },
    "ms-settings:sync": {
        "id": "ms-settings:sync",
        "domain": "ms_settings",
        "title": "Sync your settings",
        "description": "Windows Settings → Accounts → Sync. Turn on/off settings sync, theme sync, passwords sync, and other Microsoft account sync options.",
        "launch": {"kind": "uri", "value": "ms-settings:sync", "args": []},
    },
    "ms-settings:signinoptions-launchfaceenrollment": {
        "id": "ms-settings:signinoptions-launchfaceenrollment",
        "domain": "ms_settings",
        "title": "Windows Hello face enrollment",
        "description": "Windows Settings → Accounts → Sign-in options. Start Windows Hello Face setup (face recognition).",
        "launch": {"kind": "uri", "value": "ms-settings:signinoptions-launchfaceenrollment", "args": []},
    },
    "ms-settings:yourinfo": {
        "id": "ms-settings:yourinfo",
        "domain": "ms_settings",
        "title": "Your info",
        "description": "Windows Settings → Accounts → Your info. View account profile, Microsoft account details, and sign-in identity on this PC.",
        "launch": {"kind": "uri", "value": "ms-settings:yourinfo", "args": []},
    },

    # —— Apps ——
    "ms-settings:appsfeatures": {
        "id": "ms-settings:appsfeatures",
        "domain": "ms_settings",
        "title": "Apps & features",
        "description": "Windows Settings → Apps → Installed apps / Apps & features. Uninstall apps, modify apps, manage app list, app storage usage, and app repair/reset.",
        "launch": {"kind": "uri", "value": "ms-settings:appsfeatures", "args": []},
    },
    "ms-settings:appsforwebsites": {
        "id": "ms-settings:appsforwebsites",
        "domain": "ms_settings",
        "title": "Apps for websites",
        "description": "Windows Settings → Apps → Apps for websites. Choose which app opens specific links or website protocols, manage web-to-app associations.",
        "launch": {"kind": "uri", "value": "ms-settings:appsforwebsites", "args": []},
    },
    "ms-settings:defaultapps": {
        "id": "ms-settings:defaultapps",
        "domain": "ms_settings",
        "title": "Default apps",
        "description": "Windows Settings → Apps → Default apps. Set default browser, default file associations, default protocol handlers (PDF, HTTP, mailto), and per-app defaults.",
        "launch": {"kind": "uri", "value": "ms-settings:defaultapps", "args": []},
    },
    "ms-settings:optionalfeatures": {
        "id": "ms-settings:optionalfeatures",
        "domain": "ms_settings",
        "title": "Optional features",
        "description": "Windows Settings → Apps → Optional features. Add/remove Windows features, language features, RSAT, OpenSSH, Media features, and other optional components.",
        "launch": {"kind": "uri", "value": "ms-settings:optionalfeatures", "args": []},
    },
    "ms-settings:maps": {
        "id": "ms-settings:maps",
        "domain": "ms_settings",
        "title": "Offline maps",
        "description": "Windows Settings → Apps → Offline maps. Download offline maps, manage map updates, storage location for maps, and map-related permissions.",
        "launch": {"kind": "uri", "value": "ms-settings:maps", "args": []},
    },
    "ms-settings:startupapps": {
        "id": "ms-settings:startupapps",
        "domain": "ms_settings",
        "title": "Startup apps",
        "description": "Windows Settings → Apps → Startup. Enable/disable apps that run at startup, manage boot speed and startup impact.",
        "launch": {"kind": "uri", "value": "ms-settings:startupapps", "args": []},
    },
    "ms-settings:videoplayback": {
        "id": "ms-settings:videoplayback",
        "domain": "ms_settings",
        "title": "Video playback",
        "description": "Windows Settings → Apps → Video playback. Configure HDR video, battery/quality preferences, and video playback settings.",
        "launch": {"kind": "uri", "value": "ms-settings:videoplayback", "args": []},
    },

    # —— Control Center ——
    "ms-settings:controlcenter": {
        "id": "ms-settings:controlcenter",
        "domain": "ms_settings",
        "title": "Control Center / Quick settings",
        "description": "Windows Settings. Configure quick settings / control center items (Wi-Fi, Bluetooth, accessibility toggles), quick actions, and related control center options.",
        "launch": {"kind": "uri", "value": "ms-settings:controlcenter", "args": []},
    },

    # —— Cortana / Search related (legacy) ——
    "ms-settings:cortana-notifications": {
        "id": "ms-settings:cortana-notifications",
        "domain": "ms_settings",
        "title": "Cortana notifications (legacy)",
        "description": "Windows Settings → Cortana (legacy). Manage Cortana notifications and related assistant alert settings.",
        "launch": {"kind": "uri", "value": "ms-settings:cortana-notifications", "args": []},
    },
    "ms-settings:cortana-moredetails": {
        "id": "ms-settings:cortana-moredetails",
        "domain": "ms_settings",
        "title": "Cortana details (legacy)",
        "description": "Windows Settings → Cortana (legacy). View Cortana details, info, and assistant configuration pages.",
        "launch": {"kind": "uri", "value": "ms-settings:cortana-moredetails", "args": []},
    },
    "ms-settings:cortana-permissions": {
        "id": "ms-settings:cortana-permissions",
        "domain": "ms_settings",
        "title": "Cortana permissions (legacy)",
        "description": "Windows Settings → Cortana (legacy). Manage Cortana permissions, microphone access, and assistant privacy settings.",
        "launch": {"kind": "uri", "value": "ms-settings:cortana-permissions", "args": []},
    },
    "ms-settings:cortana-windowssearch": {
        "id": "ms-settings:cortana-windowssearch",
        "domain": "ms_settings",
        "title": "Cortana & Windows Search (legacy)",
        "description": "Windows Settings → Cortana (legacy). Configure Cortana integration with Windows Search and related search behavior.",
        "launch": {"kind": "uri", "value": "ms-settings:cortana-windowssearch", "args": []},
    },
    "ms-settings:cortana": {
        "id": "ms-settings:cortana",
        "domain": "ms_settings",
        "title": "Cortana (legacy)",
        "description": "Windows Settings → Cortana (legacy). Access Cortana assistant settings (older Windows versions).",
        "launch": {"kind": "uri", "value": "ms-settings:cortana", "args": []},
    },

    # —— Devices ——
    "ms-settings:autoplay": {
        "id": "ms-settings:autoplay",
        "domain": "ms_settings",
        "title": "AutoPlay",
        "description": "Windows Settings → Bluetooth & devices / Devices. Configure AutoPlay behavior for USB drives, SD cards, phones, and media insertion.",
        "launch": {"kind": "uri", "value": "ms-settings:autoplay", "args": []},
    },
    "ms-settings:bluetooth": {
        "id": "ms-settings:bluetooth",
        "domain": "ms_settings",
        "title": "Bluetooth",
        "description": "Windows Settings → Bluetooth & devices. Turn Bluetooth on/off, pair devices (headphones, mice), manage connected Bluetooth devices.",
        "launch": {"kind": "uri", "value": "ms-settings:bluetooth", "args": []},
    },
    "ms-settings:connecteddevices": {
        "id": "ms-settings:connecteddevices",
        "domain": "ms_settings",
        "title": "Connected devices",
        "description": "Windows Settings → Bluetooth & devices. View and manage connected devices (USB, Bluetooth, audio devices), device discovery and connections.",
        "launch": {"kind": "uri", "value": "ms-settings:connecteddevices", "args": []},
    },
    "ms-settings:camera": {
        "id": "ms-settings:camera",
        "domain": "ms_settings",
        "title": "Camera devices",
        "description": "Windows Settings → Bluetooth & devices. Manage camera devices, default camera selection, camera hardware settings (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:camera", "args": []},
    },
    "ms-settings:mousetouchpad": {
        "id": "ms-settings:mousetouchpad",
        "domain": "ms_settings",
        "title": "Mouse & touchpad",
        "description": "Windows Settings → Bluetooth & devices. Configure mouse speed, scrolling, touchpad sensitivity, gestures, and pointer settings.",
        "launch": {"kind": "uri", "value": "ms-settings:mousetouchpad", "args": []},
    },
    "ms-settings:pen": {
        "id": "ms-settings:pen",
        "domain": "ms_settings",
        "title": "Pen & Windows Ink",
        "description": "Windows Settings → Bluetooth & devices. Configure pen shortcuts, handwriting, pen pairing, and Windows Ink settings.",
        "launch": {"kind": "uri", "value": "ms-settings:pen", "args": []},
    },
    "ms-settings:printers": {
        "id": "ms-settings:printers",
        "domain": "ms_settings",
        "title": "Printers & scanners",
        "description": "Windows Settings → Bluetooth & devices → Printers & scanners. Add printers, manage printers and scanners, set default printer, view queues.",
        "launch": {"kind": "uri", "value": "ms-settings:printers", "args": []},
    },
    "ms-settings:devices-touch": {
        "id": "ms-settings:devices-touch",
        "domain": "ms_settings",
        "title": "Touch",
        "description": "Windows Settings → Bluetooth & devices. Configure touch input, touch gestures, touch responsiveness, and touch-related options.",
        "launch": {"kind": "uri", "value": "ms-settings:devices-touch", "args": []},
    },
    "ms-settings:devices-touchpad": {
        "id": "ms-settings:devices-touchpad",
        "domain": "ms_settings",
        "title": "Touchpad",
        "description": "Windows Settings → Bluetooth & devices → Touchpad. Configure touchpad gestures, sensitivity, taps, scrolling and zoom settings.",
        "launch": {"kind": "uri", "value": "ms-settings:devices-touchpad", "args": []},
    },
    "ms-settings:devicestyping-hwkbtextsuggestions": {
        "id": "ms-settings:devicestyping-hwkbtextsuggestions",
        "domain": "ms_settings",
        "title": "Hardware keyboard text suggestions",
        "description": "Windows Settings → Time & language / Typing. Enable text suggestions and autocorrect for hardware keyboard typing.",
        "launch": {"kind": "uri", "value": "ms-settings:devicestyping-hwkbtextsuggestions", "args": []},
    },
    "ms-settings:typing": {
        "id": "ms-settings:typing",
        "domain": "ms_settings",
        "title": "Typing",
        "description": "Windows Settings → Time & language / Typing. Configure autocorrect, text suggestions, hardware keyboard, touch keyboard behavior, and typing personalization.",
        "launch": {"kind": "uri", "value": "ms-settings:typing", "args": []},
    },
    "ms-settings:usb": {
        "id": "ms-settings:usb",
        "domain": "ms_settings",
        "title": "USB",
        "description": "Windows Settings → Bluetooth & devices → USB. Manage USB notifications, USB device behavior, and related USB options.",
        "launch": {"kind": "uri", "value": "ms-settings:usb", "args": []},
    },
    "ms-settings:wheel": {
        "id": "ms-settings:wheel",
        "domain": "ms_settings",
        "title": "Wheel (scrolling)",
        "description": "Windows Settings → Bluetooth & devices. Configure mouse wheel scrolling options and related wheel behaviors.",
        "launch": {"kind": "uri", "value": "ms-settings:wheel", "args": []},
    },
    "ms-settings:mobile-devices": {
        "id": "ms-settings:mobile-devices",
        "domain": "ms_settings",
        "title": "Mobile devices",
        "description": "Windows Settings → Bluetooth & devices. Manage mobile devices integration (phone connection, pairing, cross-device features) depending on Windows version.",
        "launch": {"kind": "uri", "value": "ms-settings:mobile-devices", "args": []},
    },

    # —— Ease of Access / Accessibility ——
    "ms-settings:easeofaccess-display": {
        "id": "ms-settings:easeofaccess-display",
        "domain": "ms_settings",
        "title": "Accessibility: Display",
        "description": "Windows Settings → Accessibility. Display accessibility options like text size, brightness-related accessibility controls, and visual accommodations.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-display", "args": []},
    },
    "ms-settings:easeofaccess-eyecontrol": {
        "id": "ms-settings:easeofaccess-eyecontrol",
        "domain": "ms_settings",
        "title": "Accessibility: Eye control",
        "description": "Windows Settings → Accessibility. Configure eye tracking / eye control features (where supported) for accessibility.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-eyecontrol", "args": []},
    },
    "ms-settings:fonts": {
        "id": "ms-settings:fonts",
        "domain": "ms_settings",
        "title": "Fonts",
        "description": "Windows Settings → Personalization / Accessibility. Manage system fonts: install fonts, preview fonts, remove fonts. Useful for 'change fonts', 'install font', '字体管理'.",
        "launch": {"kind": "uri", "value": "ms-settings:fonts", "args": []},
    },
    "ms-settings:easeofaccess-highcontrast": {
        "id": "ms-settings:easeofaccess-highcontrast",
        "domain": "ms_settings",
        "title": "Accessibility: High contrast",
        "description": "Windows Settings → Accessibility. Enable high contrast themes, improve readability, and adjust contrast settings.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-highcontrast", "args": []},
    },
    "ms-settings:easeofaccess-keyboard": {
        "id": "ms-settings:easeofaccess-keyboard",
        "domain": "ms_settings",
        "title": "Accessibility: Keyboard",
        "description": "Windows Settings → Accessibility. Sticky keys, filter keys, toggle keys, on-screen keyboard, keyboard accessibility options.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-keyboard", "args": []},
    },
    "ms-settings:easeofaccess-magnifier": {
        "id": "ms-settings:easeofaccess-magnifier",
        "domain": "ms_settings",
        "title": "Accessibility: Magnifier",
        "description": "Windows Settings → Accessibility. Magnifier zoom, lens mode, keyboard shortcuts, and magnifier behavior.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-magnifier", "args": []},
    },
    "ms-settings:easeofaccess-mouse": {
        "id": "ms-settings:easeofaccess-mouse",
        "domain": "ms_settings",
        "title": "Accessibility: Mouse",
        "description": "Windows Settings → Accessibility. Mouse accessibility, mouse keys, pointer control options for accessibility needs.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-mouse", "args": []},
    },
    "ms-settings:easeofaccess-mousepointer": {
        "id": "ms-settings:easeofaccess-mousepointer",
        "domain": "ms_settings",
        "title": "Accessibility: Mouse pointer",
        "description": "Windows Settings → Accessibility. Cursor size, pointer color, pointer visibility; helpful for 'cursor too small', 'mouse pointer color'.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-mousepointer", "args": []},
    },
    "ms-settings:easeofaccess-narrator": {
        "id": "ms-settings:easeofaccess-narrator",
        "domain": "ms_settings",
        "title": "Accessibility: Narrator",
        "description": "Windows Settings → Accessibility. Narrator screen reader settings, voice, verbosity, keyboard shortcuts.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-narrator", "args": []},
    },
    "ms-settings:easeofaccess-colorfilter": {
        "id": "ms-settings:easeofaccess-colorfilter",
        "domain": "ms_settings",
        "title": "Accessibility: Color filters",
        "description": "Windows Settings → Accessibility. Color filters for color blindness, grayscale, inverted colors; useful for 'color blind mode'.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-colorfilter", "args": []},
    },
    "ms-settings:easeofaccess-speechrecognition": {
        "id": "ms-settings:easeofaccess-speechrecognition",
        "domain": "ms_settings",
        "title": "Accessibility: Speech recognition",
        "description": "Windows Settings → Accessibility. Configure speech recognition, voice control, dictation, and speech services settings.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-speechrecognition", "args": []},
    },
    "ms-settings:easeofaccess-cursor": {
        "id": "ms-settings:easeofaccess-cursor",
        "domain": "ms_settings",
        "title": "Accessibility: Text cursor",
        "description": "Windows Settings → Accessibility. Text cursor indicator, thickness, and cursor visibility settings; helpful for 'text cursor' issues.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-cursor", "args": []},
    },
    "ms-settings:easeofaccess-visualeffects": {
        "id": "ms-settings:easeofaccess-visualeffects",
        "domain": "ms_settings",
        "title": "Accessibility: Visual effects",
        "description": "Windows Settings → Accessibility. Turn off animations, transparency, show scrollbars; useful for performance and motion sensitivity.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-visualeffects", "args": []},
    },
    "ms-settings:easeofaccess-audio": {
        "id": "ms-settings:easeofaccess-audio",
        "domain": "ms_settings",
        "title": "Accessibility: Audio",
        "description": "Windows Settings → Accessibility. Mono audio, audio alerts, hearing-related settings and accessibility audio options.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-audio", "args": []},
    },
    "ms-settings:easeofaccess-closedcaptioning": {
        "id": "ms-settings:easeofaccess-closedcaptioning",
        "domain": "ms_settings",
        "title": "Accessibility: Closed captions",
        "description": "Windows Settings → Accessibility. Caption style, font, size, colors for closed captions/subtitles.",
        "launch": {"kind": "uri", "value": "ms-settings:easeofaccess-closedcaptioning", "args": []},
    },

    # —— Extras ——
    "ms-settings:extras": {
        "id": "ms-settings:extras",
        "domain": "ms_settings",
        "title": "Extras",
        "description": "Windows Settings → Extras. Additional optional settings pages depending on Windows edition and features.",
        "launch": {"kind": "uri", "value": "ms-settings:extras", "args": []},
    },

    # —— Family ——
    "ms-settings:family-group": {
        "id": "ms-settings:family-group",
        "domain": "ms_settings",
        "title": "Family group",
        "description": "Windows Settings → Accounts → Family. Manage family members, child accounts, parental controls, and family safety features.",
        "launch": {"kind": "uri", "value": "ms-settings:family-group", "args": []},
    },

    # —— Gaming ——
    "ms-settings:gaming-gamebar": {
        "id": "ms-settings:gaming-gamebar",
        "domain": "ms_settings",
        "title": "Gaming: Game Bar",
        "description": "Windows Settings → Gaming. Configure Xbox Game Bar, shortcuts, overlays, capture controls, and game bar behavior.",
        "launch": {"kind": "uri", "value": "ms-settings:gaming-gamebar", "args": []},
    },
    "ms-settings:gaming-gamedvr": {
        "id": "ms-settings:gaming-gamedvr",
        "domain": "ms_settings",
        "title": "Gaming: Captures (Game DVR)",
        "description": "Windows Settings → Gaming. Configure game recording, capture settings, background recording, video quality and storage location.",
        "launch": {"kind": "uri", "value": "ms-settings:gaming-gamedvr", "args": []},
    },
    "ms-settings:gaming-gamemode": {
        "id": "ms-settings:gaming-gamemode",
        "domain": "ms_settings",
        "title": "Gaming: Game Mode",
        "description": "Windows Settings → Gaming. Enable/disable Game Mode to optimize performance for games, reduce background activity.",
        "launch": {"kind": "uri", "value": "ms-settings:gaming-gamemode", "args": []},
    },
    "ms-settings:quietmomentsgame": {
        "id": "ms-settings:quietmomentsgame",
        "domain": "ms_settings",
        "title": "Focus assist: Gaming (Quiet moments)",
        "description": "Windows Settings → System → Focus assist (legacy quiet moments). Configure notifications suppression while gaming.",
        "launch": {"kind": "uri", "value": "ms-settings:quietmomentsgame", "args": []},
    },

    # —— Mixed Reality ——
    "ms-settings:holographic-audio": {
        "id": "ms-settings:holographic-audio",
        "domain": "ms_settings",
        "title": "Mixed Reality: Audio",
        "description": "Windows Settings → Mixed reality. Configure mixed reality audio settings for headsets and spatial audio.",
        "launch": {"kind": "uri", "value": "ms-settings:holographic-audio", "args": []},
    },
    "ms-settings:privacy-holographic-environment": {
        "id": "ms-settings:privacy-holographic-environment",
        "domain": "ms_settings",
        "title": "Mixed Reality privacy: Environment",
        "description": "Windows Settings → Privacy / Mixed Reality. Manage environment data and privacy settings related to mixed reality.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-holographic-environment", "args": []},
    },
    "ms-settings:holographic-headset": {
        "id": "ms-settings:holographic-headset",
        "domain": "ms_settings",
        "title": "Mixed Reality: Headset display",
        "description": "Windows Settings → Mixed reality. Headset display options, calibration, and headset configuration (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:holographic-headset", "args": []},
    },
    "ms-settings:holographic-management": {
        "id": "ms-settings:holographic-management",
        "domain": "ms_settings",
        "title": "Mixed Reality: Management",
        "description": "Windows Settings → Mixed reality. Manage mixed reality features, environment, setup and device management.",
        "launch": {"kind": "uri", "value": "ms-settings:holographic-management", "args": []},
    },
    "ms-settings:holographic-startupandesktop": {
        "id": "ms-settings:holographic-startupandesktop",
        "domain": "ms_settings",
        "title": "Mixed Reality: Startup & desktop",
        "description": "Windows Settings → Mixed reality. Configure startup and desktop behavior for mixed reality experiences.",
        "launch": {"kind": "uri", "value": "ms-settings:holographic-startupandesktop", "args": []},
    },

    # —— Network & Internet ——
    "ms-settings:network-status": {
        "id": "ms-settings:network-status",
        "domain": "ms_settings",
        "title": "Network status",
        "description": "Windows Settings → Network & internet. View connection status, troubleshoot network, see IP info, connectivity issues, and network properties.",
        "launch": {"kind": "uri", "value": "ms-settings:network-status", "args": []},
    },
    "ms-settings:network-advancedsettings": {
        "id": "ms-settings:network-advancedsettings",
        "domain": "ms_settings",
        "title": "Advanced network settings",
        "description": "Windows Settings → Network & internet → Advanced network settings. Adapter options, network reset, advanced sharing settings links, and network profiles.",
        "launch": {"kind": "uri", "value": "ms-settings:network-advancedsettings", "args": []},
    },
    "ms-settings:network-airplanemode": {
        "id": "ms-settings:network-airplanemode",
        "domain": "ms_settings",
        "title": "Airplane mode",
        "description": "Windows Settings → Network & internet. Toggle airplane mode, disable radios, manage wireless communications quickly.",
        "launch": {"kind": "uri", "value": "ms-settings:network-airplanemode", "args": []},
    },
    "ms-settings:network-cellular": {
        "id": "ms-settings:network-cellular",
        "domain": "ms_settings",
        "title": "Cellular",
        "description": "Windows Settings → Network & internet. Cellular data / SIM settings (LTE/5G), data usage, roaming, APN (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:network-cellular", "args": []},
    },
    "ms-settings:network-dialup": {
        "id": "ms-settings:network-dialup",
        "domain": "ms_settings",
        "title": "Dial-up",
        "description": "Windows Settings → Network & internet. Dial-up connections and legacy modem networking configuration.",
        "launch": {"kind": "uri", "value": "ms-settings:network-dialup", "args": []},
    },
    "ms-settings:network-directaccess": {
        "id": "ms-settings:network-directaccess",
        "domain": "ms_settings",
        "title": "DirectAccess (enterprise)",
        "description": "Windows Settings → Network & internet. DirectAccess enterprise connectivity settings (where available).",
        "launch": {"kind": "uri", "value": "ms-settings:network-directaccess", "args": []},
    },
    "ms-settings:network-ethernet": {
        "id": "ms-settings:network-ethernet",
        "domain": "ms_settings",
        "title": "Ethernet",
        "description": "Windows Settings → Network & internet. Wired network (Ethernet) configuration, IP settings, DNS, proxy links, and adapter properties.",
        "launch": {"kind": "uri", "value": "ms-settings:network-ethernet", "args": []},
    },
    "ms-settings:network-wifisettings": {
        "id": "ms-settings:network-wifisettings",
        "domain": "ms_settings",
        "title": "Wi-Fi settings",
        "description": "Windows Settings → Network & internet → Wi-Fi (settings). Manage Wi-Fi adapters, known networks, connect/disconnect, Wi-Fi properties.",
        "launch": {"kind": "uri", "value": "ms-settings:network-wifisettings", "args": []},
    },
    "ms-settings:network-mobilehotspot": {
        "id": "ms-settings:network-mobilehotspot",
        "domain": "ms_settings",
        "title": "Mobile hotspot",
        "description": "Windows Settings → Network & internet. Turn on mobile hotspot, share internet over Wi-Fi/Bluetooth, configure hotspot name/password.",
        "launch": {"kind": "uri", "value": "ms-settings:network-mobilehotspot", "args": []},
    },
    "ms-settings:network-proxy": {
        "id": "ms-settings:network-proxy",
        "domain": "ms_settings",
        "title": "Proxy",
        "description": "Windows Settings → Network & internet. Configure proxy server, automatic proxy setup (PAC), manual proxy, and related networking settings.",
        "launch": {"kind": "uri", "value": "ms-settings:network-proxy", "args": []},
    },
    "ms-settings:network-vpn": {
        "id": "ms-settings:network-vpn",
        "domain": "ms_settings",
        "title": "VPN",
        "description": "Windows Settings → Network & internet. Add VPN profile, connect/disconnect VPN, manage VPN credentials and VPN adapter options.",
        "launch": {"kind": "uri", "value": "ms-settings:network-vpn", "args": []},
    },
    "ms-settings:network-wifi": {
        "id": "ms-settings:network-wifi",
        "domain": "ms_settings",
        "title": "Wi-Fi",
        "description": "Windows Settings → Network & internet. Wi-Fi connect/disconnect, available networks, manage Wi-Fi settings, 'connect to wifi', 'wifi not working'.",
        "launch": {"kind": "uri", "value": "ms-settings:network-wifi", "args": []},
    },
    "ms-settings:wifi-provisioning": {
        "id": "ms-settings:wifi-provisioning",
        "domain": "ms_settings",
        "title": "Wi-Fi provisioning",
        "description": "Windows Settings → Network & internet. Wi-Fi provisioning and enterprise Wi-Fi setup (QR/code provisioning where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:wifi-provisioning", "args": []},
    },

    # —— Personalization ——
    "ms-settings:personalization-background": {
        "id": "ms-settings:personalization-background",
        "domain": "ms_settings",
        "title": "Background / Wallpaper",
        "description": "Windows Settings → Personalization → Background. Change wallpaper, background picture, slideshow, and desktop background settings.",
        "launch": {"kind": "uri", "value": "ms-settings:personalization-background", "args": []},
    },
    "ms-settings:personalization-start-places": {
        "id": "ms-settings:personalization-start-places",
        "domain": "ms_settings",
        "title": "Start: Folders / Places",
        "description": "Windows Settings → Personalization → Start. Choose which folders appear on Start, pinned places, Start menu folder shortcuts.",
        "launch": {"kind": "uri", "value": "ms-settings:personalization-start-places", "args": []},
    },
    "ms-settings:colors": {
        "id": "ms-settings:colors",
        "domain": "ms_settings",
        "title": "Colors (theme colors)",
        "description": "Windows Settings → Personalization → Colors. Change accent color, light/dark mode, transparency effects; useful for 'dark mode', 'change accent color'.",
        "launch": {"kind": "uri", "value": "ms-settings:colors", "args": []},
    },
    "ms-settings:lockscreen": {
        "id": "ms-settings:lockscreen",
        "domain": "ms_settings",
        "title": "Lock screen",
        "description": "Windows Settings → Personalization → Lock screen. Change lock screen background, screen timeout links, lock screen notifications, and widgets (depending on version).",
        "launch": {"kind": "uri", "value": "ms-settings:lockscreen", "args": []},
    },
    "ms-settings:personalization": {
        "id": "ms-settings:personalization",
        "domain": "ms_settings",
        "title": "Personalization (home)",
        "description": "Windows Settings → Personalization. Main personalization hub: background, colors, lock screen, themes, Start, taskbar, fonts.",
        "launch": {"kind": "uri", "value": "ms-settings:personalization", "args": []},
    },
    "ms-settings:personalization-start": {
        "id": "ms-settings:personalization-start",
        "domain": "ms_settings",
        "title": "Start",
        "description": "Windows Settings → Personalization → Start. Configure Start menu layout, pinned items, recommendations, and Start behavior.",
        "launch": {"kind": "uri", "value": "ms-settings:personalization-start", "args": []},
    },
    "ms-settings:taskbar": {
        "id": "ms-settings:taskbar",
        "domain": "ms_settings",
        "title": "Taskbar",
        "description": "Windows Settings → Personalization → Taskbar. Taskbar icons, alignment, system tray, auto-hide, taskbar behaviors, 'change taskbar'.",
        "launch": {"kind": "uri", "value": "ms-settings:taskbar", "args": []},
    },
    "ms-settings:personalization-touchkeyboard": {
        "id": "ms-settings:personalization-touchkeyboard",
        "domain": "ms_settings",
        "title": "Touch keyboard",
        "description": "Windows Settings → Personalization. Customize touch keyboard theme, size, and layout; useful for 'touch keyboard style'.",
        "launch": {"kind": "uri", "value": "ms-settings:personalization-touchkeyboard", "args": []},
    },
    "ms-settings:themes": {
        "id": "ms-settings:themes",
        "domain": "ms_settings",
        "title": "Themes",
        "description": "Windows Settings → Personalization → Themes. Change themes, sounds, mouse cursor theme links, and related theme settings.",
        "launch": {"kind": "uri", "value": "ms-settings:themes", "args": []},
    },

    # —— Phone ——
    "ms-settings:deviceusage": {
        "id": "ms-settings:deviceusage",
        "domain": "ms_settings",
        "title": "Device usage / Phone integration",
        "description": "Windows Settings. Configure device usage experiences and integrations, including phone linking/cross-device features (varies by Windows version).",
        "launch": {"kind": "uri", "value": "ms-settings:deviceusage", "args": []},
    },

    # —— Privacy ——
    "ms-settings:privacy-accountinfo": {
        "id": "ms-settings:privacy-accountinfo",
        "domain": "ms_settings",
        "title": "Privacy: Account info",
        "description": "Windows Settings → Privacy & security / Privacy. Manage which apps can access your account info and identity information.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-accountinfo", "args": []},
    },
    "ms-settings:privacy-activityhistory": {
        "id": "ms-settings:privacy-activityhistory",
        "domain": "ms_settings",
        "title": "Privacy: Activity history",
        "description": "Windows Settings → Privacy & security / Privacy. Control activity history collection and syncing, timeline-like history settings.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-activityhistory", "args": []},
    },
    "ms-settings:privacy-appdiagnostics": {
        "id": "ms-settings:privacy-appdiagnostics",
        "domain": "ms_settings",
        "title": "Privacy: App diagnostics",
        "description": "Windows Settings → Privacy & security / Privacy. Manage app diagnostics access permissions for apps.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-appdiagnostics", "args": []},
    },
    "ms-settings:privacy-automaticfiledownloads": {
        "id": "ms-settings:privacy-automaticfiledownloads",
        "domain": "ms_settings",
        "title": "Privacy: Automatic file downloads",
        "description": "Windows Settings → Privacy & security / Privacy. Control automatic file downloads permission per app and related settings.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-automaticfiledownloads", "args": []},
    },
    "ms-settings:privacy-backgroundapps": {
        "id": "ms-settings:privacy-backgroundapps",
        "domain": "ms_settings",
        "title": "Privacy: Background apps",
        "description": "Windows Settings → Privacy & security / Privacy. Control whether apps run in the background; reduce and background activity.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-backgroundapps", "args": []},
    },
    "ms-settings:privacy-backgroundspatialperception": {
        "id": "ms-settings:privacy-backgroundspatialperception",
        "domain": "ms_settings",
        "title": "Privacy: Spatial perception (Mixed Reality)",
        "description": "Windows Settings → Privacy & security / Privacy. Control spatial perception data used by mixed reality features (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-backgroundspatialperception", "args": []},
    },
    "ms-settings:privacy-calendar": {
        "id": "ms-settings:privacy-calendar",
        "domain": "ms_settings",
        "title": "Privacy: Calendar",
        "description": "Windows Settings → Privacy & security / Privacy. Control calendar access permissions for apps.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-calendar", "args": []},
    },
    "ms-settings:privacy-callhistory": {
        "id": "ms-settings:privacy-callhistory",
        "domain": "ms_settings",
        "title": "Privacy: Call history",
        "description": "Windows Settings → Privacy & security / Privacy. Control call history access permissions (telephony features where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-callhistory", "args": []},
    },
    "ms-settings:privacy-webcam": {
        "id": "ms-settings:privacy-webcam",
        "domain": "ms_settings",
        "title": "Privacy: Camera",
        "description": "Windows Settings → Privacy & security / Privacy. Allow/deny camera access per app; useful for 'camera permission', 'webcam blocked'.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-webcam", "args": []},
    },
    "ms-settings:privacy-contacts": {
        "id": "ms-settings:privacy-contacts",
        "domain": "ms_settings",
        "title": "Privacy: Contacts",
        "description": "Windows Settings → Privacy & security / Privacy. Control contacts access permissions for apps.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-contacts", "args": []},
    },
    "ms-settings:privacy-documents": {
        "id": "ms-settings:privacy-documents",
        "domain": "ms_settings",
        "title": "Privacy: Documents",
        "description": "Windows Settings → Privacy & security / Privacy. Control documents library access permissions for apps.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-documents", "args": []},
    },
    "ms-settings:privacy-downloadsfolder": {
        "id": "ms-settings:privacy-downloadsfolder",
        "domain": "ms_settings",
        "title": "Privacy: Downloads folder",
        "description": "Windows Settings → Privacy & security / Privacy. Control Downloads folder access permissions for apps.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-downloadsfolder", "args": []},
    },
    "ms-settings:privacy-email": {
        "id": "ms-settings:privacy-email",
        "domain": "ms_settings",
        "title": "Privacy: Email",
        "description": "Windows Settings → Privacy & security / Privacy. Control email access permissions for apps.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-email", "args": []},
    },
    "ms-settings:privacy-eyetracker": {
        "id": "ms-settings:privacy-eyetracker",
        "domain": "ms_settings",
        "title": "Privacy: Eye tracker",
        "description": "Windows Settings → Privacy & security / Privacy. Control eye-tracking device access permissions (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-eyetracker", "args": []},
    },
    "ms-settings:privacy-feedback": {
        "id": "ms-settings:privacy-feedback",
        "domain": "ms_settings",
        "title": "Privacy: Diagnostics & feedback (legacy link)",
        "description": "Windows Settings → Privacy & security / Privacy. Manage feedback frequency, diagnostic data, and related privacy feedback controls (varies by version).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-feedback", "args": []},
    },
    "ms-settings:privacy-broadfilesystemaccess": {
        "id": "ms-settings:privacy-broadfilesystemaccess",
        "domain": "ms_settings",
        "title": "Privacy: File system (broad access)",
        "description": "Windows Settings → Privacy & security / Privacy. Allow apps broad file system access; control per-app permission.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-broadfilesystemaccess", "args": []},
    },
    "ms-settings:privacy": {
        "id": "ms-settings:privacy",
        "domain": "ms_settings",
        "title": "Privacy (home)",
        "description": "Windows Settings → Privacy & security / Privacy. Main privacy hub; app permissions, diagnostics, and privacy controls.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy", "args": []},
    },
    "ms-settings:privacy-general": {
        "id": "ms-settings:privacy-general",
        "domain": "ms_settings",
        "title": "Privacy: General",
        "description": "Windows Settings → Privacy & security / Privacy. General privacy options: advertising ID, language list, diagnostics toggles, and content suggestions.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-general", "args": []},
    },
    "ms-settings:privacy-graphicscaptureprogrammatic": {
        "id": "ms-settings:privacy-graphicscaptureprogrammatic",
        "domain": "ms_settings",
        "title": "Privacy: Screen capture (programmatic)",
        "description": "Windows Settings → Privacy & security / Privacy. Control which apps can capture the screen programmatically (screen capture permission).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-graphicscaptureprogrammatic", "args": []},
    },
    "ms-settings:privacy-graphicscapturewithoutborder": {
        "id": "ms-settings:privacy-graphicscapturewithoutborder",
        "domain": "ms_settings",
        "title": "Privacy: Screen capture without border",
        "description": "Windows Settings → Privacy & security / Privacy. Configure permissions for borderless screen capture (when supported).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-graphicscapturewithoutborder", "args": []},
    },
    "ms-settings:privacy-speechtyping": {
        "id": "ms-settings:privacy-speechtyping",
        "domain": "ms_settings",
        "title": "Privacy: Speech & typing personalization",
        "description": "Windows Settings → Privacy & security / Privacy. Control speech recognition and typing personalization data and privacy.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-speechtyping", "args": []},
    },
    "ms-settings:privacy-location": {
        "id": "ms-settings:privacy-location",
        "domain": "ms_settings",
        "title": "Privacy: Location",
        "description": "Windows Settings → Privacy & security / Privacy. Turn location on/off, location permissions per app, location history, 'location access'.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-location", "args": []},
    },
    "ms-settings:privacy-messaging": {
        "id": "ms-settings:privacy-messaging",
        "domain": "ms_settings",
        "title": "Privacy: Messaging",
        "description": "Windows Settings → Privacy & security / Privacy. Control messaging/SMS access permissions (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-messaging", "args": []},
    },
    "ms-settings:privacy-microphone": {
        "id": "ms-settings:privacy-microphone",
        "domain": "ms_settings",
        "title": "Privacy: Microphone",
        "description": "Windows Settings → Privacy & security / Privacy. Allow/deny microphone access per app; useful for 'mic not working', 'microphone permission'.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-microphone", "args": []},
    },
    "ms-settings:privacy-motion": {
        "id": "ms-settings:privacy-motion",
        "domain": "ms_settings",
        "title": "Privacy: Motion",
        "description": "Windows Settings → Privacy & security / Privacy. Control motion sensor access permissions (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-motion", "args": []},
    },
    "ms-settings:privacy-musiclibrary": {
        "id": "ms-settings:privacy-musiclibrary",
        "domain": "ms_settings",
        "title": "Privacy: Music library",
        "description": "Windows Settings → Privacy & security / Privacy. Control music library access permissions for apps.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-musiclibrary", "args": []},
    },
    "ms-settings:privacy-notifications": {
        "id": "ms-settings:privacy-notifications",
        "domain": "ms_settings",
        "title": "Privacy: Notifications",
        "description": "Windows Settings → Privacy & security / Privacy. Manage notifications access and privacy-related notification permissions (varies by version).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-notifications", "args": []},
    },
    "ms-settings:privacy-customdevices": {
        "id": "ms-settings:privacy-customdevices",
        "domain": "ms_settings",
        "title": "Privacy: Custom devices",
        "description": "Windows Settings → Privacy & security / Privacy. Control app access to custom devices and device interfaces (enterprise/advanced scenarios).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-customdevices", "args": []},
    },
    "ms-settings:privacy-phonecalls": {
        "id": "ms-settings:privacy-phonecalls",
        "domain": "ms_settings",
        "title": "Privacy: Phone calls",
        "description": "Windows Settings → Privacy & security / Privacy. Control access to phone call features (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-phonecalls", "args": []},
    },
    "ms-settings:privacy-pictures": {
        "id": "ms-settings:privacy-pictures",
        "domain": "ms_settings",
        "title": "Privacy: Pictures",
        "description": "Windows Settings → Privacy & security / Privacy. Control pictures library access permissions for apps.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-pictures", "args": []},
    },
    "ms-settings:privacy-radios": {
        "id": "ms-settings:privacy-radios",
        "domain": "ms_settings",
        "title": "Privacy: Radios",
        "description": "Windows Settings → Privacy & security / Privacy. Control app access to radios (Bluetooth, Wi-Fi, etc.) (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-radios", "args": []},
    },
    "ms-settings:privacy-speech": {
        "id": "ms-settings:privacy-speech",
        "domain": "ms_settings",
        "title": "Privacy: Speech",
        "description": "Windows Settings → Privacy & security / Privacy. Manage online speech recognition, speech services, and privacy controls.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-speech", "args": []},
    },
    "ms-settings:privacy-tasks": {
        "id": "ms-settings:privacy-tasks",
        "domain": "ms_settings",
        "title": "Privacy: Tasks",
        "description": "Windows Settings → Privacy & security / Privacy. Control tasks access permissions for apps (To Do, tasks integration).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-tasks", "args": []},
    },
    "ms-settings:privacy-videos": {
        "id": "ms-settings:privacy-videos",
        "domain": "ms_settings",
        "title": "Privacy: Videos",
        "description": "Windows Settings → Privacy & security / Privacy. Control videos library access permissions for apps.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-videos", "args": []},
    },
    "ms-settings:privacy-voice": {
        "id": "ms-settings:privacy-voice",
        "domain": "ms_settings",
        "title": "Privacy: Voice (legacy)",
        "description": "Windows Settings → Privacy & security / Privacy. Legacy voice/voice activation privacy settings (older page naming).",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-voice", "args": []},
    },
    "ms-settings:privacy-voiceactivation": {
        "id": "ms-settings:privacy-voiceactivation",
        "domain": "ms_settings",
        "title": "Privacy: Voice activation",
        "description": "Windows Settings → Privacy & security / Privacy. Control voice activation / wake word permissions per app and voice assistants.",
        "launch": {"kind": "uri", "value": "ms-settings:privacy-voiceactivation", "args": []},
    },

    # —— Search ——
    "ms-settings:search": {
        "id": "ms-settings:search",
        "domain": "ms_settings",
        "title": "Search (home)",
        "description": "Windows Settings → Privacy & security / Search. Configure Windows Search behavior, indexing, search highlights, and search settings.",
        "launch": {"kind": "uri", "value": "ms-settings:search", "args": []},
    },
    "ms-settings:search-moredetails": {
        "id": "ms-settings:search-moredetails",
        "domain": "ms_settings",
        "title": "Search: More details",
        "description": "Windows Settings → Search. Additional Search details and configuration pages (varies by Windows version).",
        "launch": {"kind": "uri", "value": "ms-settings:search-moredetails", "args": []},
    },
    "ms-settings:search-permissions": {
        "id": "ms-settings:search-permissions",
        "domain": "ms_settings",
        "title": "Search: Permissions & history",
        "description": "Windows Settings → Search. Manage search permissions, safe search, cloud content search, and search history.",
        "launch": {"kind": "uri", "value": "ms-settings:search-permissions", "args": []},
    },

    # —— Surface Hub ——
    "ms-settings:surfacehub-accounts": {
        "id": "ms-settings:surfacehub-accounts",
        "domain": "ms_settings",
        "title": "Surface Hub: Accounts",
        "description": "Windows Settings → Surface Hub. Configure accounts and sign-in settings for Surface Hub devices.",
        "launch": {"kind": "uri", "value": "ms-settings:surfacehub-accounts", "args": []},
    },
    "ms-settings:surfacehub-sessioncleanup": {
        "id": "ms-settings:surfacehub-sessioncleanup",
        "domain": "ms_settings",
        "title": "Surface Hub: Session cleanup",
        "description": "Windows Settings → Surface Hub. Configure session cleanup policies and data clearing for shared Surface Hub sessions.",
        "launch": {"kind": "uri", "value": "ms-settings:surfacehub-sessioncleanup", "args": []},
    },
    "ms-settings:surfacehub-calling": {
        "id": "ms-settings:surfacehub-calling",
        "domain": "ms_settings",
        "title": "Surface Hub: Calling",
        "description": "Windows Settings → Surface Hub. Configure calling settings and audio/video call behavior on Surface Hub.",
        "launch": {"kind": "uri", "value": "ms-settings:surfacehub-calling", "args": []},
    },
    "ms-settings:surfacehub-devicemanagenent": {
        "id": "ms-settings:surfacehub-devicemanagenent",
        "domain": "ms_settings",
        "title": "Surface Hub: Device management",
        "description": "Windows Settings → Surface Hub. Device management options for Surface Hub (MDM/management integration).",
        "launch": {"kind": "uri", "value": "ms-settings:surfacehub-devicemanagenent", "args": []},
    },
    "ms-settings:surfacehub-welcome": {
        "id": "ms-settings:surfacehub-welcome",
        "domain": "ms_settings",
        "title": "Surface Hub: Welcome",
        "description": "Windows Settings → Surface Hub. Welcome/setup experience for Surface Hub devices.",
        "launch": {"kind": "uri", "value": "ms-settings:surfacehub-welcome", "args": []},
    },

    # —— System ——
    "ms-settings:about": {
        "id": "ms-settings:about",
        "domain": "ms_settings",
        "title": "About (device specifications)",
        "description": "Windows Settings → System → About. View device specs (CPU, RAM, device name), Windows version, rename PC, and system info basics.",
        "launch": {"kind": "uri", "value": "ms-settings:about", "args": []},
    },
    "ms-settings:display-advanced": {
        "id": "ms-settings:display-advanced",
        "domain": "ms_settings",
        "title": "Advanced display",
        "description": "Windows Settings → System → Display → Advanced display. Refresh rate, monitor info, display adapter properties, HDR capabilities.",
        "launch": {"kind": "uri", "value": "ms-settings:display-advanced", "args": []},
    },
    "ms-settings:apps-volume": {
        "id": "ms-settings:apps-volume",
        "domain": "ms_settings",
        "title": "App volume & device preferences",
        "description": "Windows Settings → System → Sound. Adjust per-app volume, output/input device per app, volume mixer; useful for 'app volume'.",
        "launch": {"kind": "uri", "value": "ms-settings:apps-volume", "args": []},
    },
    "ms-settings:batterysaver": {
        "id": "ms-settings:batterysaver",
        "domain": "ms_settings",
        "title": "Battery saver",
        "description": "Windows Settings → System → Power & battery. Battery saver toggle and quick settings for saving power and extending battery life.",
        "launch": {"kind": "uri", "value": "ms-settings:batterysaver", "args": []},
    },
    "ms-settings:batterysaver-settings": {
        "id": "ms-settings:batterysaver-settings",
        "domain": "ms_settings",
        "title": "Battery saver settings",
        "description": "Windows Settings → System → Power & battery. Battery saver behavior, thresholds, and background activity limits.",
        "launch": {"kind": "uri", "value": "ms-settings:batterysaver-settings", "args": []},
    },
    "ms-settings:batterysaver-usagedetails": {
        "id": "ms-settings:batterysaver-usagedetails",
        "domain": "ms_settings",
        "title": "Battery usage details",
        "description": "Windows Settings → System → Power & battery. Battery usage by app, power usage history, battery drain troubleshooting.",
        "launch": {"kind": "uri", "value": "ms-settings:batterysaver-usagedetails", "args": []},
    },
    "ms-settings:clipboard": {
        "id": "ms-settings:clipboard",
        "domain": "ms_settings",
        "title": "Clipboard",
        "description": "Windows Settings → System → Clipboard. Clipboard history, sync across devices, clear clipboard, and clipboard settings.",
        "launch": {"kind": "uri", "value": "ms-settings:clipboard", "args": []},
    },
    "ms-settings:display": {
        "id": "ms-settings:display",
        "domain": "ms_settings",
        "title": "Display (brightness, resolution, scaling)",
        "description": "Windows Settings → System → Display. Change screen brightness, scaling, resolution, orientation, HDR, multiple monitors; useful for 'screen too dark', 'change brightness'.",
        "launch": {"kind": "uri", "value": "ms-settings:display", "args": []},
    },
    "ms-settings:savelocations": {
        "id": "ms-settings:savelocations",
        "domain": "ms_settings",
        "title": "Storage: Save locations",
        "description": "Windows Settings → System → Storage. Choose where new content is saved (apps, documents, music), default save locations.",
        "launch": {"kind": "uri", "value": "ms-settings:savelocations", "args": []},
    },
    "ms-settings:screenrotation": {
        "id": "ms-settings:screenrotation",
        "domain": "ms_settings",
        "title": "Screen rotation",
        "description": "Windows Settings → System → Display. Screen rotation lock and rotation settings for tablets/convertibles.",
        "launch": {"kind": "uri", "value": "ms-settings:screenrotation", "args": []},
    },
    "ms-settings:quietmomentspresentation": {
        "id": "ms-settings:quietmomentspresentation",
        "domain": "ms_settings",
        "title": "Focus assist: Presentation (Quiet moments)",
        "description": "Windows Settings → System → Focus assist. Configure focus/quiet hours behavior while presenting.",
        "launch": {"kind": "uri", "value": "ms-settings:quietmomentspresentation", "args": []},
    },
    "ms-settings:quietmomentsscheduled": {
        "id": "ms-settings:quietmomentsscheduled",
        "domain": "ms_settings",
        "title": "Focus assist: Scheduled (Quiet moments)",
        "description": "Windows Settings → System → Focus assist. Set schedules for focus/quiet hours and notification suppression.",
        "launch": {"kind": "uri", "value": "ms-settings:quietmomentsscheduled", "args": []},
    },
    "ms-settings:deviceencryption": {
        "id": "ms-settings:deviceencryption",
        "domain": "ms_settings",
        "title": "Device encryption",
        "description": "Windows Settings → Privacy & security / System. Device encryption settings (where supported), manage encryption status and requirements.",
        "launch": {"kind": "uri", "value": "ms-settings:deviceencryption", "args": []},
    },
    "ms-settings:energyrecommendations": {
        "id": "ms-settings:energyrecommendations",
        "domain": "ms_settings",
        "title": "Energy recommendations",
        "description": "Windows Settings → System → Power & battery. Energy recommendations to reduce power usage and improve battery life.",
        "launch": {"kind": "uri", "value": "ms-settings:energyrecommendations", "args": []},
    },
    "ms-settings:quiethours": {
        "id": "ms-settings:quiethours",
        "domain": "ms_settings",
        "title": "Focus assist / Quiet hours",
        "description": "Windows Settings → System → Focus assist. Configure quiet hours/focus assist to reduce notifications and distractions.",
        "launch": {"kind": "uri", "value": "ms-settings:quiethours", "args": []},
    },
    "ms-settings:display-advancedgraphics": {
        "id": "ms-settings:display-advancedgraphics",
        "domain": "ms_settings",
        "title": "Graphics settings",
        "description": "Windows Settings → System → Display → Graphics. Per-app GPU preference, hardware-accelerated GPU scheduling (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:display-advancedgraphics", "args": []},
    },
    "ms-settings:display-advancedgraphics-default": {
        "id": "ms-settings:display-advancedgraphics-default",
        "domain": "ms_settings",
        "title": "Graphics default settings",
        "description": "Windows Settings → System → Display → Graphics. Default graphics settings and global GPU preferences (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:display-advancedgraphics-default", "args": []},
    },
    "ms-settings:multitasking": {
        "id": "ms-settings:multitasking",
        "domain": "ms_settings",
        "title": "Multitasking",
        "description": "Windows Settings → System → Multitasking. Snap windows, virtual desktops behavior, multitasking settings.",
        "launch": {"kind": "uri", "value": "ms-settings:multitasking", "args": []},
    },
    "ms-settings:nightlight": {
        "id": "ms-settings:nightlight",
        "domain": "ms_settings",
        "title": "Night light (blue light filter)",
        "description": "Windows Settings → System → Display. Night light reduces blue light / changes color temperature for eye comfort at night; not the main brightness control.",
        "launch": {"kind": "uri", "value": "ms-settings:nightlight", "args": []},
    },
    "ms-settings:project": {
        "id": "ms-settings:project",
        "domain": "ms_settings",
        "title": "Projecting to this PC / Display projection",
        "description": "Windows Settings → System. Project to this PC, connect to wireless displays, screen mirroring, 'project screen', 'second monitor'.",
        "launch": {"kind": "uri", "value": "ms-settings:project", "args": []},
    },
    "ms-settings:crossdevice": {
        "id": "ms-settings:crossdevice",
        "domain": "ms_settings",
        "title": "Cross-device experiences",
        "description": "Windows Settings → System. Cross-device experiences, shared clipboard, phone link integration, and device handoff features.",
        "launch": {"kind": "uri", "value": "ms-settings:crossdevice", "args": []},
    },
    "ms-settings:notifications": {
        "id": "ms-settings:notifications",
        "domain": "ms_settings",
        "title": "Notifications",
        "description": "Windows Settings → System → Notifications. Configure notification settings, do not disturb/focus, app notifications, notification sounds.",
        "launch": {"kind": "uri", "value": "ms-settings:notifications", "args": []},
    },
    "ms-settings:remotedesktop": {
        "id": "ms-settings:remotedesktop",
        "domain": "ms_settings",
        "title": "Remote Desktop",
        "description": "Windows Settings → System → Remote Desktop. Enable Remote Desktop, configure RDP access, remote connections, and remote desktop settings.",
        "launch": {"kind": "uri", "value": "ms-settings:remotedesktop", "args": []},
    },
    "ms-settings:powersleep": {
        "id": "ms-settings:powersleep",
        "domain": "ms_settings",
        "title": "Power & sleep",
        "description": "Windows Settings → System → Power & battery / Power & sleep. Screen timeout, sleep settings, power behavior; useful for 'screen turns off', 'sleep too fast'.",
        "launch": {"kind": "uri", "value": "ms-settings:powersleep", "args": []},
    },
    "ms-settings:presence": {
        "id": "ms-settings:presence",
        "domain": "ms_settings",
        "title": "Presence sensing",
        "description": "Windows Settings → System. Presence sensing and related device presence features (where supported).",
        "launch": {"kind": "uri", "value": "ms-settings:presence", "args": []},
    },
    "ms-settings:sound": {
        "id": "ms-settings:sound",
        "domain": "ms_settings",
        "title": "Sound",
        "description": "Windows Settings → System → Sound. Output/input device selection, volume, microphone, sound enhancements, troubleshoot audio; useful for 'no sound'.",
        "launch": {"kind": "uri", "value": "ms-settings:sound", "args": []},
    },
    "ms-settings:sound-devices": {
        "id": "ms-settings:sound-devices",
        "domain": "ms_settings",
        "title": "Sound devices",
        "description": "Windows Settings → System → Sound → All sound devices. Manage speakers, headphones, microphones, input/output devices and properties.",
        "launch": {"kind": "uri", "value": "ms-settings:sound-devices", "args": []},
    },
    "ms-settings:sound-defaultinputproperties": {
        "id": "ms-settings:sound-defaultinputproperties",
        "domain": "ms_settings",
        "title": "Default input device properties",
        "description": "Windows Settings → System → Sound. Configure default microphone/input device properties and settings.",
        "launch": {"kind": "uri", "value": "ms-settings:sound-defaultinputproperties", "args": []},
    },
    "ms-settings:sound-defaultoutputproperties": {
        "id": "ms-settings:sound-defaultoutputproperties",
        "domain": "ms_settings",
        "title": "Default output device properties",
        "description": "Windows Settings → System → Sound. Configure default speaker/output device properties and settings.",
        "launch": {"kind": "uri", "value": "ms-settings:sound-defaultoutputproperties", "args": []},
    },
    "ms-settings:storagesense": {
        "id": "ms-settings:storagesense",
        "domain": "ms_settings",
        "title": "Storage Sense",
        "description": "Windows Settings → System → Storage Sense. Automatically free disk space, clean temporary files, manage storage cleanup schedules.",
        "launch": {"kind": "uri", "value": "ms-settings:storagesense", "args": []},
    },
    "ms-settings:storagepolicies": {
        "id": "ms-settings:storagepolicies",
        "domain": "ms_settings",
        "title": "Storage policies",
        "description": "Windows Settings → System → Storage. Storage policies and advanced storage rules (varies by Windows version/edition).",
        "launch": {"kind": "uri", "value": "ms-settings:storagepolicies", "args": []},
    },
    "ms-settings:storagerecommendations": {
        "id": "ms-settings:storagerecommendations",
        "domain": "ms_settings",
        "title": "Storage recommendations",
        "description": "Windows Settings → System → Storage. Recommendations to free disk space, remove unused files/apps; useful for 'free up space'.",
        "launch": {"kind": "uri", "value": "ms-settings:storagerecommendations", "args": []},
    },
    "ms-settings:disksandvolumes": {
        "id": "ms-settings:disksandvolumes",
        "domain": "ms_settings",
        "title": "Disks & volumes",
        "description": "Windows Settings → System → Storage → Disks & volumes. View disks, volumes, partitions; basic disk/volume management (not full Disk Management).",
        "launch": {"kind": "uri", "value": "ms-settings:disksandvolumes", "args": []},
    },

    # —— Time & Language ——
    "ms-settings:dateandtime": {
        "id": "ms-settings:dateandtime",
        "domain": "ms_settings",
        "title": "Date & time",
        "description": "Windows Settings → Time & language. Set time, time zone, automatic time sync, daylight saving, and date/time formats.",
        "launch": {"kind": "uri", "value": "ms-settings:dateandtime", "args": []},
    },
    "ms-settings:regionformatting": {
        "id": "ms-settings:regionformatting",
        "domain": "ms_settings",
        "title": "Region formatting",
        "description": "Windows Settings → Time & language. Configure region formats, date/time number formats, local format preferences.",
        "launch": {"kind": "uri", "value": "ms-settings:regionformatting", "args": []},
    },
    "ms-settings:keyboard": {
        "id": "ms-settings:keyboard",
        "domain": "ms_settings",
        "title": "Keyboard",
        "description": "Windows Settings → Time & language → Typing/Keyboard. Configure keyboard layout, repeat rate, advanced keyboard settings links.",
        "launch": {"kind": "uri", "value": "ms-settings:keyboard", "args": []},
    },
    "ms-settings:speech": {
        "id": "ms-settings:speech",
        "domain": "ms_settings",
        "title": "Speech",
        "description": "Windows Settings → Time & language. Configure speech recognition, voice, speech language, and speech services settings.",
        "launch": {"kind": "uri", "value": "ms-settings:speech", "args": []},
    },
    "ms-settings:regionlanguage-adddisplaylanguage": {
        "id": "ms-settings:regionlanguage-adddisplaylanguage",
        "domain": "ms_settings",
        "title": "Add a display language",
        "description": "Windows Settings → Time & language → Language. Add display language packs; useful for 'install language pack', 'add display language'.",
        "launch": {"kind": "uri", "value": "ms-settings:regionlanguage-adddisplaylanguage", "args": []},
    },
    "ms-settings:regionlanguage-languageoptions": {
        "id": "ms-settings:regionlanguage-languageoptions",
        "domain": "ms_settings",
        "title": "Language options",
        "description": "Windows Settings → Time & language → Language. Language options: keyboard layouts, handwriting, speech, and regional language features.",
        "launch": {"kind": "uri", "value": "ms-settings:regionlanguage-languageoptions", "args": []},
    },
    "ms-settings:regionlanguage-setdisplaylanguage": {
        "id": "ms-settings:regionlanguage-setdisplaylanguage",
        "domain": "ms_settings",
        "title": "Set display language",
        "description": "Windows Settings → Time & language → Language. Set Windows display language; useful for 'change system language'.",
        "launch": {"kind": "uri", "value": "ms-settings:regionlanguage-setdisplaylanguage", "args": []},
    },

    # —— Update & Security ——
    "ms-settings:activation": {
        "id": "ms-settings:activation",
        "domain": "ms_settings",
        "title": "Activation",
        "description": "Windows Settings → System / Update & security. Windows activation status, product key, activation troubleshooting.",
        "launch": {"kind": "uri", "value": "ms-settings:activation", "args": []},
    },
    "ms-settings:backup": {
        "id": "ms-settings:backup",
        "domain": "ms_settings",
        "title": "Backup",
        "description": "Windows Settings → Accounts / System. Backup settings, Windows backup options, OneDrive backup, file backup links.",
        "launch": {"kind": "uri", "value": "ms-settings:backup", "args": []},
    },
    "ms-settings:delivery-optimization": {
        "id": "ms-settings:delivery-optimization",
        "domain": "ms_settings",
        "title": "Delivery Optimization",
        "description": "Windows Settings → Windows Update. Delivery Optimization: download updates from other PCs, bandwidth limits, update delivery settings.",
        "launch": {"kind": "uri", "value": "ms-settings:delivery-optimization", "args": []},
    },
    "ms-settings:findmydevice": {
        "id": "ms-settings:findmydevice",
        "domain": "ms_settings",
        "title": "Find my device",
        "description": "Windows Settings → Privacy & security / Update & security. Find my device: locate device, enable tracking; not for hardware specs.",
        "launch": {"kind": "uri", "value": "ms-settings:findmydevice", "args": []},
    },
    "ms-settings:developers": {
        "id": "ms-settings:developers",
        "domain": "ms_settings",
        "title": "For developers",
        "description": "Windows Settings → Privacy & security. Developer settings: developer mode, device portal, app sideloading, advanced developer options.",
        "launch": {"kind": "uri", "value": "ms-settings:developers", "args": []},
    },
    "ms-settings:recovery": {
        "id": "ms-settings:recovery",
        "domain": "ms_settings",
        "title": "Recovery",
        "description": "Windows Settings → System → Recovery. Reset this PC, advanced startup, recovery options, rollback, and troubleshooting recovery tools.",
        "launch": {"kind": "uri", "value": "ms-settings:recovery", "args": []},
    },
    "ms-settings:signinoptions-launchsecuritykeyenrollment": {
        "id": "ms-settings:signinoptions-launchsecuritykeyenrollment",
        "domain": "ms_settings",
        "title": "Security key enrollment",
        "description": "Windows Settings → Accounts → Sign-in options. Enroll a security key (FIDO2) for sign-in.",
        "launch": {"kind": "uri", "value": "ms-settings:signinoptions-launchsecuritykeyenrollment", "args": []},
    },
    "ms-settings:troubleshoot": {
        "id": "ms-settings:troubleshoot",
        "domain": "ms_settings",
        "title": "Troubleshoot",
        "description": "Windows Settings → System → Troubleshoot. Run troubleshooters, recommended troubleshooting, fix common PC issues.",
        "launch": {"kind": "uri", "value": "ms-settings:troubleshoot", "args": []},
    },
    "ms-settings:windowsdefender": {
        "id": "ms-settings:windowsdefender",
        "domain": "ms_settings",
        "title": "Windows Security / Defender",
        "description": "Windows Settings → Privacy & security. Open Windows Security/Defender settings: virus protection, firewall links, security dashboard.",
        "launch": {"kind": "uri", "value": "ms-settings:windowsdefender", "args": []},
    },
    "ms-settings:windowsinsider": {
        "id": "ms-settings:windowsinsider",
        "domain": "ms_settings",
        "title": "Windows Insider Program",
        "description": "Windows Settings → Windows Update. Insider Program enrollment, preview builds, insider settings.",
        "launch": {"kind": "uri", "value": "ms-settings:windowsinsider", "args": []},
    },
    "ms-settings:windowsupdate": {
        "id": "ms-settings:windowsupdate",
        "domain": "ms_settings",
        "title": "Windows Update",
        "description": "Windows Settings → Windows Update. Check for updates, download/install updates, update status, pause updates.",
        "launch": {"kind": "uri", "value": "ms-settings:windowsupdate", "args": []},
    },
    "ms-settings:windowsupdate-activehours": {
        "id": "ms-settings:windowsupdate-activehours",
        "domain": "ms_settings",
        "title": "Windows Update: Active hours",
        "description": "Windows Settings → Windows Update. Configure active hours to prevent restarts during work hours.",
        "launch": {"kind": "uri", "value": "ms-settings:windowsupdate-activehours", "args": []},
    },
    "ms-settings:windowsupdate-options": {
        "id": "ms-settings:windowsupdate-options",
        "domain": "ms_settings",
        "title": "Windows Update: Advanced options",
        "description": "Windows Settings → Windows Update. Advanced update options: restart behavior, update notifications, optional updates links.",
        "launch": {"kind": "uri", "value": "ms-settings:windowsupdate-options", "args": []},
    },
    "ms-settings:windowsupdate-optionalupdates": {
        "id": "ms-settings:windowsupdate-optionalupdates",
        "domain": "ms_settings",
        "title": "Windows Update: Optional updates",
        "description": "Windows Settings → Windows Update. View and install optional updates, driver updates, feature updates.",
        "launch": {"kind": "uri", "value": "ms-settings:windowsupdate-optionalupdates", "args": []},
    },
    "ms-settings:windowsupdate-restartoptions": {
        "id": "ms-settings:windowsupdate-restartoptions",
        "domain": "ms_settings",
        "title": "Windows Update: Restart options",
        "description": "Windows Settings → Windows Update. Configure restart schedule, restart notifications, and update restart settings.",
        "launch": {"kind": "uri", "value": "ms-settings:windowsupdate-restartoptions", "args": []},
    },
    "ms-settings:windowsupdate-seekerondemand": {
        "id": "ms-settings:windowsupdate-seekerondemand",
        "domain": "ms_settings",
        "title": "Windows Update: Seek on demand",
        "description": "Windows Settings → Windows Update. Manually seek updates or on-demand update behavior (varies by version).",
        "launch": {"kind": "uri", "value": "ms-settings:windowsupdate-seekerondemand", "args": []},
    },
    "ms-settings:windowsupdate-history": {
        "id": "ms-settings:windowsupdate-history",
        "domain": "ms_settings",
        "title": "Windows Update: Update history",
        "description": "Windows Settings → Windows Update. View update history, installed updates, failed updates, uninstall updates links.",
        "launch": {"kind": "uri", "value": "ms-settings:windowsupdate-history", "args": []},
    },

    # —— User Accounts / Workplace ——
    "ms-settings:workplace-provisioning": {
        "id": "ms-settings:workplace-provisioning",
        "domain": "ms_settings",
        "title": "Workplace provisioning",
        "description": "Windows Settings → Accounts / Workplace. Provisioning settings for work/school enrollment and enterprise provisioning.",
        "launch": {"kind": "uri", "value": "ms-settings:workplace-provisioning", "args": []},
    },
    "ms-settings:workplace-repairtoken": {
        "id": "ms-settings:workplace-repairtoken",
        "domain": "ms_settings",
        "title": "Workplace repair token",
        "description": "Windows Settings → Accounts / Workplace. Repair token or workplace enrollment repair (enterprise scenarios).",
        "launch": {"kind": "uri", "value": "ms-settings:workplace-repairtoken", "args": []},
    },
    "ms-settings:provisioning": {
        "id": "ms-settings:provisioning",
        "domain": "ms_settings",
        "title": "Provisioning",
        "description": "Windows Settings. Provisioning packages and configuration provisioning (enterprise deployment scenarios).",
        "launch": {"kind": "uri", "value": "ms-settings:provisioning", "args": []},
    },
    "ms-settings:windowsanywhere": {
        "id": "ms-settings:windowsanywhere",
        "domain": "ms_settings",
        "title": "Windows Anywhere / Mobile device management (legacy)",
        "description": "Windows Settings. Windows Anywhere / roaming or device management features (legacy/enterprise, varies by Windows version).",
        "launch": {"kind": "uri", "value": "ms-settings:windowsanywhere", "args": []},
    },

    # —— Settings Home (root) ——
    "ms-settings:": {
        "id": "ms-settings:",
        "domain": "ms_settings",
        "title": "Settings (home)",
        "description": "Windows Settings home page. Open the main Settings app root / home screen.",
        "launch": {"kind": "uri", "value": "ms-settings:", "args": []},
    },
}


CONTROL_PANEL_ITEMS = {
    # --- System & Security ---
    "system": {
        "id": "system",
        "domain": "control_panel",
        "title": "System",
        "description": "Control Panel → System. View basic PC information: Windows edition, processor (CPU), installed RAM (memory), device name, system type.",
        "launch": {"kind": "control_name", "value": "Microsoft.System", "args": []},
    },
    "security_and_maintenance": {
        "id": "security_and_maintenance",
        "domain": "control_panel",
        "title": "Security and Maintenance",
        "description": "Control Panel → Security and Maintenance. View security status, maintenance messages, reliability and system health notifications.",
        "launch": {"kind": "control_name", "value": "Microsoft.ActionCenter", "args": []},
    },
    "windows_defender_firewall": {
        "id": "windows_defender_firewall",
        "domain": "control_panel",
        "title": "Windows Defender Firewall",
        "description": "Control Panel → Windows Defender Firewall. Firewall rules basics, allow apps, network profile firewall, 'open firewall'.",
        "launch": {"kind": "control_name", "value": "Microsoft.WindowsFirewall", "args": []},
    },
    "bitlocker_drive_encryption": {
        "id": "bitlocker_drive_encryption",
        "domain": "control_panel",
        "title": "BitLocker Drive Encryption",
        "description": "Control Panel → BitLocker Drive Encryption. Enable/manage BitLocker, encrypt drives, recovery keys, device encryption controls.",
        "launch": {"kind": "control_name", "value": "Microsoft.BitLockerDriveEncryption", "args": []},
    },

    # --- Network and Internet ---
    "network_and_sharing_center": {
        "id": "network_and_sharing_center",
        "domain": "control_panel",
        "title": "Network and Sharing Center",
        "description": "Control Panel → Network and Sharing Center. Legacy networking hub: view network status, adapter settings links, sharing settings.",
        "launch": {"kind": "control_name", "value": "Microsoft.NetworkAndSharingCenter", "args": []},
    },
    "internet_options": {
        "id": "internet_options",
        "domain": "control_panel",
        "title": "Internet Options",
        "description": "Control Panel → Internet Options. Proxy/connection settings, security zones, privacy, certificates; useful for legacy IE/WinInet settings.",
        "launch": {"kind": "control_name", "value": "Microsoft.InternetOptions", "args": []},
    },

    # --- Hardware and Sound ---
    "devices_and_printers": {
        "id": "devices_and_printers",
        "domain": "control_panel",
        "title": "Devices and Printers",
        "description": "Control Panel → Devices and Printers. Legacy devices view: printers, scanners, Bluetooth devices; useful for troubleshooting device installs.",
        "launch": {"kind": "control_name", "value": "Microsoft.DevicesAndPrinters", "args": []},
    },
    "mouse": {
        "id": "mouse",
        "domain": "control_panel",
        "title": "Mouse Properties",
        "description": "Mouse Properties (main.cpl). Configure pointer speed, buttons, wheel, double-click speed, and mouse hardware settings.",
        "launch": {"kind": "cpl", "value": "main.cpl", "args": []},
    },
    "keyboard": {
        "id": "keyboard",
        "domain": "control_panel",
        "title": "Keyboard",
        "description": "Control Panel → Keyboard. Configure keyboard repeat delay/rate and keyboard-related classic settings.",
        "launch": {"kind": "control_name", "value": "Microsoft.Keyboard", "args": []},
    },
    "sound": {
        "id": "sound",
        "domain": "control_panel",
        "title": "Sound",
        "description": "Control Panel → Sound. Classic sound device control panel: playback/recording devices, default device, enhancements (legacy).",
        "launch": {"kind": "control_name", "value": "Microsoft.Sound", "args": []},
    },
    "power_options": {
        "id": "power_options",
        "domain": "control_panel",
        "title": "Power Options",
        "description": "Control Panel → Power Options (powercfg.cpl). Change power plan, power mode (battery saver vs high performance), lid close action, sleep settings.",
        "launch": {"kind": "cpl", "value": "powercfg.cpl", "args": []},
    },

    # --- Programs ---
    "programs_and_features": {
        "id": "programs_and_features",
        "domain": "control_panel",
        "title": "Programs and Features",
        "description": "Programs and Features (appwiz.cpl). Uninstall or change a program, manage installed desktop apps, turn Windows features on/off links.",
        "launch": {"kind": "cpl", "value": "appwiz.cpl", "args": []},
    },
    "default_programs": {
        "id": "default_programs",
        "domain": "control_panel",
        "title": "Default Programs (legacy)",
        "description": "Control Panel → Default Programs. Legacy default app associations and defaults management (older UI).",
        "launch": {"kind": "control_name", "value": "Microsoft.DefaultPrograms", "args": []},
    },

    # --- User Accounts ---
    "user_accounts": {
        "id": "user_accounts",
        "domain": "control_panel",
        "title": "User Accounts",
        "description": "Control Panel → User Accounts. Manage local accounts, credential changes, account types, and classic user account settings.",
        "launch": {"kind": "control_name", "value": "Microsoft.UserAccounts", "args": []},
    },
    "credential_manager": {
        "id": "credential_manager",
        "domain": "control_panel",
        "title": "Credential Manager",
        "description": "Control Panel → Credential Manager. Manage Windows credentials, saved passwords, web credentials, and enterprise credentials.",
        "launch": {"kind": "control_name", "value": "Microsoft.CredentialManager", "args": []},
    },

    # --- Appearance and Personalization ---
    "display": {
        "id": "display",
        "domain": "control_panel",
        "title": "Display (legacy)",
        "description": "Control Panel → Display (legacy). Classic display settings entry point on older Windows versions; may link to scaling and display options.",
        "launch": {"kind": "control_name", "value": "Microsoft.Display", "args": []},
    },
    "fonts": {
        "id": "fonts",
        "domain": "control_panel",
        "title": "Fonts (classic)",
        "description": "Control Panel → Fonts. Classic font management: install/remove fonts, font preview (legacy). Useful for '字体', 'install font'.",
        "launch": {"kind": "control_name", "value": "Microsoft.Fonts", "args": []},
    },

    # --- Clock and Region ---
    "date_and_time": {
        "id": "date_and_time",
        "domain": "control_panel",
        "title": "Date and Time",
        "description": "Date and Time (timedate.cpl). Change date, time, time zone, internet time sync (classic UI).",
        "launch": {"kind": "cpl", "value": "timedate.cpl", "args": []},
    },
    "region": {
        "id": "region",
        "domain": "control_panel",
        "title": "Region",
        "description": "Control Panel → Region. Regional formats, location, administrative language settings (classic). Useful for 'region format'.",
        "launch": {"kind": "control_name", "value": "Microsoft.RegionAndLanguage", "args": []},
    },

    # --- Ease of Access ---
    "ease_of_access_center": {
        "id": "ease_of_access_center",
        "domain": "control_panel",
        "title": "Ease of Access Center",
        "description": "Control Panel → Ease of Access Center. Classic accessibility settings hub (narrator, magnifier, high contrast links).",
        "launch": {"kind": "control_name", "value": "Microsoft.EaseOfAccessCenter", "args": []},
    },

    # --- Storage ---
    "storage_spaces": {
        "id": "storage_spaces",
        "domain": "control_panel",
        "title": "Storage Spaces",
        "description": "Control Panel → Storage Spaces. Create/manage storage pools and storage spaces (software RAID-like).",
        "launch": {"kind": "control_name", "value": "Microsoft.StorageSpaces", "args": []},
    },
    "file_history": {
        "id": "file_history",
        "domain": "control_panel",
        "title": "File History",
        "description": "Control Panel → File History. Configure file backup history to external drive/network location (classic backup feature).",
        "launch": {"kind": "control_name", "value": "Microsoft.FileHistory", "args": []},
    },

    # --- Root entry ---
    "control_panel_home": {
        "id": "control_panel_home",
        "domain": "control_panel",
        "title": "Control Panel (home)",
        "description": "Open Control Panel home page (classic Control Panel root). Useful for browsing classic settings.",
        "launch": {"kind": "control_home", "value": "", "args": []},
    },
}


SYSTEM_TOOL_ITEMS = {
    "system_information": {
        "id": "system_information",
        "domain": "system_tool",
        "title": "System Information",
        "description": "Open System Information. View system info / system summary / hardware info / BIOS version / drivers / CPU info / CPU frequency / memory speed / memory size / memory frequency. useful for 'check memory speed', 'check RAM info', 'check hardware info'",
        "launch": {"kind": "exe", "value": "msinfo32.exe", "args": []},
    },
    # --- Tasks / Performance / Logs ---
    "task_manager": {
        "id": "task_manager",
        "domain": "system_tool",
        "title": "Task Manager",
        "description": "Task Manager (taskmgr.exe). View running processes, CPU/GPU/RAM usage, startup apps, kill tasks; useful for 'high CPU', 'memory usage'.",
        "launch": {"kind": "exe", "value": "taskmgr.exe", "args": []},
    },
    "resource_monitor": {
        "id": "resource_monitor",
        "domain": "system_tool",
        "title": "Resource Monitor",
        "description": "Resource Monitor (resmon.exe). Detailed CPU, disk, network, memory usage; troubleshoot performance bottlenecks.",
        "launch": {"kind": "exe", "value": "resmon.exe", "args": []},
    },
    "performance_monitor": {
        "id": "performance_monitor",
        "domain": "system_tool",
        "title": "Performance Monitor",
        "description": "Performance Monitor (perfmon.msc). Advanced performance counters, CPU frequency/usage graphs, data collector sets; useful for 'current CPU frequency', 'performance'.",
        "launch": {"kind": "msc", "value": "perfmon.msc", "args": []},
    },
    "event_viewer": {
        "id": "event_viewer",
        "domain": "system_tool",
        "title": "Event Viewer",
        "description": "Event Viewer (eventvwr.msc). View Windows logs, system/application/security events; troubleshoot errors and crashes.",
        "launch": {"kind": "msc", "value": "eventvwr.msc", "args": []},
    },

    # --- Disk / Storage ---
    "disk_management": {
        "id": "disk_management",
        "domain": "system_tool",
        "title": "Disk Management",
        "description": "Disk Management (diskmgmt.msc). Manage partitions, volumes, drive letters, initialize disks; useful for 'disk management', 'partition'.",
        "launch": {"kind": "msc", "value": "diskmgmt.msc", "args": []},
    },
    "disk_cleanup": {
        "id": "disk_cleanup",
        "domain": "system_tool",
        "title": "Disk Cleanup",
        "description": "Disk Cleanup (cleanmgr.exe). Clean temporary files, system files, free disk space; useful for 'clean disk', 'free up space'.",
        "launch": {"kind": "exe", "value": "cleanmgr.exe", "args": []},
    },

    # --- Devices / Services ---
    "device_manager": {
        "id": "device_manager",
        "domain": "system_tool",
        "title": "Device Manager",
        "description": "Device Manager (devmgmt.msc). View hardware devices, drivers, device status; update/rollback drivers; useful for 'hardware info'.",
        "launch": {"kind": "msc", "value": "devmgmt.msc", "args": []},
    },
    "services": {
        "id": "services",
        "domain": "system_tool",
        "title": "Services",
        "description": "Services console (services.msc). Manage Windows services: start/stop, set startup type, troubleshoot service issues.",
        "launch": {"kind": "msc", "value": "services.msc", "args": []},
    },
    "computer_management": {
        "id": "computer_management",
        "domain": "system_tool",
        "title": "Computer Management",
        "description": "Computer Management (compmgmt.msc). Administrative console: event viewer, disk management, shared folders, users/groups (varies), services.",
        "launch": {"kind": "msc", "value": "compmgmt.msc", "args": []},
    },

    # --- System configuration & registry ---
    "system_configuration": {
        "id": "system_configuration",
        "domain": "system_tool",
        "title": "System Configuration (msconfig)",
        "description": "System Configuration (msconfig.exe). Manage boot options, startup selection, services startup; useful for troubleshooting boot and startup issues.",
        "launch": {"kind": "exe", "value": "msconfig.exe", "args": []},
    },
    "registry_editor": {
        "id": "registry_editor",
        "domain": "system_tool",
        "title": "Registry Editor",
        "description": "Registry Editor (regedit.exe). Advanced system configuration in Windows registry (high-risk). Useful for 'open registry'.",
        "launch": {"kind": "exe", "value": "regedit.exe", "args": []},
    },

    # --- Command line & PowerShell ---
    "command_prompt": {
        "id": "command_prompt",
        "domain": "system_tool",
        "title": "Command Prompt",
        "description": "Command Prompt (cmd.exe). Open classic terminal for command-line tasks, scripting, networking commands.",
        "launch": {"kind": "exe", "value": "cmd.exe", "args": []},
    },
    "powershell": {
        "id": "powershell",
        "domain": "system_tool",
        "title": "Windows PowerShell",
        "description": "PowerShell (powershell.exe). Open PowerShell terminal for automation, scripts, admin commands, diagnostics.",
        "launch": {"kind": "exe", "value": "powershell.exe", "args": []},
    },

    # --- Other common tools ---
    "notepad": {
        "id": "notepad",
        "domain": "system_tool",
        "title": "Notepad",
        "description": "Notepad (notepad.exe). Simple text editor; useful for quick notes or editing config files.",
        "launch": {"kind": "exe", "value": "notepad.exe", "args": []},
    },
    "snipping_tool": {
        "id": "snipping_tool",
        "domain": "system_tool",
        "title": "Snipping Tool",
        "description": "Snipping Tool (SnippingTool.exe). Take screenshots, screen snips, annotate captures; useful for 'screenshot'.",
        "launch": {"kind": "exe", "value": "SnippingTool.exe", "args": []},
    },
}