QUESTION_POOL = [
    "show system info",
    "check my hardware information",
    "my screen is too dark",
    "open Display Settings",
    "I want to rotate my screen",
    "check my hardware info",
    "check CPU info",
    "check my RAM info",
    "check my memory speed",
    "open task manager",
    "open the resource monitor",
    "I want to see my PC Performance",
    "clean my disk",
    "manage my disk",
    "change my storage settings",
    "change my Wi-Fi connection",
    "check my bluetooth",
    "check my proxy settings",
    "change my VPN settings",
    "the music is too loud",
    "change my system language",
    "change the mouse settings",
    "change the power mode",
    "check the power options",
    "is there any windows update?",
    "where is my device",
    "open windows services",
]